# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-176387624-1'

menu:
- {name: 'My body transformation', folder: 'pages', file: 'MBT.html'}
- {name: 'My business story', folder: 'pages', file: 'My_Business_story'}
- {name: 'The BIG journey', folder: 'pages', file: 'The_BiG_Journey'}
- {name: 'My bucket list', folder: 'pages', file: 'documentation.html'}
- {name: 'People that inspire me', folder: 'pages', file: 'about.html'}
- {name: 'My biggest f**kups', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:

- {icon: 'facebook', link: 'https://www.facebook.com/1ntotheunknown'}
- {icon: 'instagram', link: 'https://www.instagram.com/1n2theunknown/'}
- {icon: 'envelope', link: 'mailto:1n2theunknownblog@gmail.com'}

# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
